#!/usr/bin/env bash
# script that displays back luck on 4th loop good luck on 8th loop and best school on the other loops
x=1
while [ $x -le 20 ]
do
echo "$x"
case $x in 
		"4")
			echo "bad luck from China"
			;;
		"9")
		echo "bad luck from Japan"
		;;
	"17")
		echo "bad luck from Italy"
		;;
esac
((x++))
done
